### ISSUE TITLE
Witherproofed: Ghasts do not drop gunpowder or tears

### ISSUE THREAD

**Issue by Johannason** [Sajeyson-Dev/ShiftedLib#1]
I'd have posted on the issue page for Witherproofed itself, but that's 404'd.

Ghostly Essence is the only drop for ghasts with Witherproofed installed. I'm not sure if Witherproofed specifically is responsible, but the other mobs that drop Witherproofed resources also appear to have their normal drops removed.

Wither Skeletons only drop Ghostly Essence. (I still get Skulls and Skull fragments due to another mod)

I haven't fought a Wither yet, but according to JustEnoughResources it would only drop Withered Powder. Will test this soon.

MC 1.18.2
forge-1.18.2-40.2.0
Witherproofed-2.6.3-1.18.2

**Comment by Johannason** [comment]
Follow-up: the wither does not spawn when summoned the usual way. Four blocks of soul sand, three wither skulls, nothing happens. I'm not sure if that's related.

**Comment by sajeyson012** [comment]
Know about the drops, currently working on Witherproofed. Also rewriting/improving ShiftedLib (almost done). 

About the wither summoning, make sure you place skull as last block and make sure there is no blocks below those floating two soul sand blocks. Also I do literally nothing with wither at all, only adding drops, which is a datapack/loottable (json), no code involved.

**Comment by Johannason** [comment]
I am aware of how the Wither should be summoned.  
With Witherproofed installed, it does not work. After removing Witherproofed, it does not work.  
After removing Witherproofed and starting a new world, making no other changes, it works with the exact same structure in the exact same place.

It doesn't make any sense to me either, I'm just reporting the issue.

**Comment by sajeyson012** [comment]
Did you get log errors like 'Unable to create new entity' or something like that? Also, do you tried to reproduce issue with only Witherproofed installed?
